services:
  pocketbase:
    image: nephazz/gamescore-keeper-pocketbase
    build: pocketbase
    ports:
      - "8090:8080"
    volumes:
      - ./pocketbase/pb_migrations:/pb/pb_migrations
      - ./pocketbase/pb_data:/pb/pb_data

  webapp:
    image: nephazz/gamescore-keeper-frontend
    build: webapp
    ports:
      - "3000:80"
